### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nurikk** [rheinwerk-verlag/pganonymize#41]
Hi, @hkage! Can you please release a new version with latest changes?

**Comment by hkage** [comment]
Hi @nurikk 

I didn't find the time to invest some time in this project besides our current internal and urgent projects. I will try to make the last changes for the project renaming and release a new version in the next days.

**Comment by hkage** [comment]
Version 0.8.0 has been release: see https://pypi.org/project/pganonymize/0.8.0/

**Comment by nurikk** [comment]
thanks

**Comment by hkage** [comment]
You are welcome!
